version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - godox
    - ireturn
    - lll
    - paralleltest
    - perfsprint
    - tparallel
    - wrapcheck
    - wsl
    - wsl_v5
    - funcorder
    - noinlineerr
  settings:
    revive:
      rules:
        - name: comment-spacings
    staticcheck:
      checks:
        - all
        - -ST1000
    varnamelen:
      ignore-names:
        - tt
        - id
        - ip
      ignore-decls:
        - c *http.Client
        - t *testing.T
        - f *os.File
        - w http.ResponseWriter
        - r *http.Request
        - err error
        - ctx context.Context
        - fs *pflag.FlagSet
        - m *machine.Machine
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - gocyclo
          - gosec
          - varnamelen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
